[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "cmd-impl-debug"
edition     = "2021"
homepage    = "https://subalfred.hack.ink"
license     = "GPL-3.0"
name        = "cmd-impl-debug"
readme      = "README.md"
repository  = "https://github.com/hack-ink/subalfred"
version     = "0.0.0"

[dependencies]
cmd-impl = { version = "0.9.0-rc16", path = "..", features = ["debug"] }

[workspace]
exclude = []
