[book]
authors      = ["Xavier Lau"]
language     = "en"
multilingual = false
src          = "src"
title        = "Subalfred Book"

[output.html]
default-theme        = "ayu"
edit-url-template    = "https://github.com/hack-ink/subalfred/edit/main/doc/{path}"
git-repository-url   = "https://github.com/hack-ink/subalfred/tree/main/doc"
preferred-dark-theme = "ayu"
site-url             = "/subalfred/"
