[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "subrpcer-impl"
edition     = "2021"
homepage    = "https://subalfred.hack.ink"
license     = "GPL-3.0"
name        = "subrpcer-impl"
readme      = "README.md"
repository  = "https://github.com/l2ust/subalfred"
version     = "0.9.0"

[lib]
proc-macro = true

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
proc-macro2 = { version = "1.0" }
quote       = { version = "1.0" }
syn         = { version = "1.0", features = ["full"] }

[features]
debug = [
	# crates.io
	"syn/extra-traits",
]
